### ISSUE TITLE
Add -y to automatically download requirements

### ISSUE THREAD

**Issue by balyedi** [mertoalex/song-cmd#1]
https://github.com/mertoalex/song-cmd/blob/916b04503269314f2610ce89d1d498b7f74979fe/install.sh#L27
to
	2) sudo apt-get update && sudo apt-get -y upgrade && sudo apt-get install -y youtube-dl ffmpeg ;;
would be good.

**Comment by mertoalex** [comment]
(yanlışıkla kapadım lan

**Comment by mertoalex** [comment]
(GİNE)

**Comment by mertoalex** [comment]
I deleted this my stupid opinion
It's don't need to be upgrade just need update
